source: src
title: مهدی صادقی
motto: در مورد نرم‌افزار و ایده‌هایم
author: مهدی صادقی
email: mehdi@mehdix.ir
baseurl: "" # the subpath of your site, e.g. /blog
url: https://mehdix.ir # the base hostname & protocol for your site
keywords: کامپیوتر برنامه‌نویسی پایتون تکنولوژی مهندسی ایران وب
copyright: Commons Attribution 4.0 International
description: >
  سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام.

long_description: > # this means to ignore newlines until "baseurl:"
  بچه که بودیم همیشه برای بازی خونه می‌ساختیم. حالا هم نمونه‌اش رو در وب ساختم.
  اینجا سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام است،
  بویژه راه‌حل‌های مهندسی که باعث رشد و پیشرفتم شده است و می‌تواند مورد استفاده دیگران هم قرار بگیرد.

twitter:
  username: msadeghii
github:
  username: mehdisadeghi
  repository: mehdix.ir
favicon: assets/img/me.png
logo: assets/img/me.png

theme: jekyll-theme-mehdix-rtl

permalink: :title.html
timezone: Europe/Berlin

paginate: 20
paginate_path: /page:num/

tag_page_layout: tag_page
tag_page_dir: tag

collections:
  projects:
    output: true

comment_system: static
#disqus_shortname: mehdix
#google_analytics_id: UA-57282325-1
#feedburner_id: mehdixir


defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
-
  scope:
    path: "projects"
    type: "pages"
  values:
    layout: "project"

navbar:
  items:
    - projects
